### ISSUE TITLE
Model/Agent Checkpoints

### ISSUE THREAD

**Issue by deepankarkansal** [leox1v/FirstTextWorldProblems#3]
Hey Leo,

I am not able to find the code to save the _**model checkpoints**_. Can you please help me with that! 

Also while training I am getting the below error:

0% 0/1 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "FirstTextWorldProblems/train.py", line 148, in <module>
    Trainer(args.games).train()
  File "FirstTextWorldProblems/train.py", line 122, in train
    commands = self.agent.act(obs, scores, dones, infos)
  File "/content/FirstTextWorldProblems/custom_agent.py", line 184, in act
    batch_idx=idx)
  File "/content/FirstTextWorldProblems/custom_agent.py", line 208, in model_update
    self._a2c_update(value, batch_idx)
  File "/content/FirstTextWorldProblems/custom_agent.py", line 262, in _a2c_update
    self.model_loss.backward(retain_graph=True)
  File "/usr/local/lib/python3.7/dist-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/__init__.py", line 149, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [768, 256]] is at version 3; expected version 2 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

Hope you will respond ASAP.

Regards
Deepankar

**Comment by deepankarkansal** [comment]
> Hey Leo,
> 
> I am not able to find the code to save the _**model checkpoints**_. Can you please help me with that!
> 
> Also while training I am getting the below error:
> 
> 0% 0/1 [00:01<?, ?it/s] Traceback (most recent call last): File "FirstTextWorldProblems/train.py", line 148, in Trainer(args.games).train() File "FirstTextWorldProblems/train.py", line 122, in train commands = self.agent.act(obs, scores, dones, infos) File "/content/FirstTextWorldProblems/custom_agent.py", line 184, in act batch_idx=idx) File "/content/FirstTextWorldProblems/custom_agent.py", line 208, in model_update self._a2c_update(value, batch_idx) File "/content/FirstTextWorldProblems/custom_agent.py", line 262, in _a2c_update self.model_loss.backward(retain_graph=True) File "/usr/local/lib/python3.7/dist-packages/torch/_tensor.py", line 255, in backward torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs) File "/usr/local/lib/python3.7/dist-packages/torch/autograd/**init**.py", line 149, in backward allow_unreachable=True, accumulate_grad=True) # allow_unreachable flag RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [768, 256]] is at version 3; expected version 2 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
> 
> Hope you will respond ASAP.
> 
> Regards Deepankar

This error is resolved by downgrading the torch to 1.4.0 version.
